### ISSUE TITLE
gh does not resolve to a valid hostname? possibly your .ssh/config has an entry for gh but not everybody does.. :)

### ISSUE THREAD

**Issue by sunilnandihalli** [artagnon/rhine-ml#15]
sunil@Vostro-2520:~/clojure-projects/rhine$ make
git submodule update --init
Cloning into 'llvm'...
ssh: Could not resolve hostname gh: No address associated with hostname
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'gh:llvm-mirror/llvm' into submodule path 'llvm' failed
make: **\* [llvm/configure] Error 1

**Comment by artagnon** [comment]
It's actually a url.*.insteadOf in my gitconfig. Thanks for reporting! It's fixed now?

**Comment by sunilnandihalli** [comment]
Thanks That fixed it! :)
