### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by sunilnandihalli** [artagnon/rhine-ml#16]
clang++ `llvm-config --cxxflags` -c -o rgc_printer.o rgc_printer.cc
ocamlfind ocamlc -g -w @5@8@10@11@12@14@23@24@26@29@40 -package llvm -package llvm.executionengine \
    -package llvm.analysis -package llvm.target -package llvm.scalar_opts \
    -package core -thread -package textutils -package bytes \
    -linkpkg location.cmo ast_helper.cmo parser.cmo lexer.cmo pretty.cmo cookast.cmo codegen.cmo mlunbox.cmo toplevel.cmo main.cmo bindings.o rgc.o rgc_printer.o -o rhine
rgc.o:(.data.rel.ro._ZTIN12_GLOBAL__N_13RgcE+0x10): undefined reference to `typeinfo for llvm::GCStrategy'
rgc_printer.o: In function`RgcPrinter':
/home/sunil/clojure-projects/rhine/rgc_printer.cc:12: undefined reference to `llvm::GCMetadataPrinter::GCMetadataPrinter()'
rgc_printer.o: In function`~RgcPrinter':
/home/sunil/clojure-projects/rhine/rgc_printer.cc:12: undefined reference to `llvm::GCMetadataPrinter::~GCMetadataPrinter()'
rgc_printer.o:(.data.rel.ro._ZTVN12_GLOBAL__N_110RgcPrinterE+0x20): undefined reference to`llvm::GCMetadataPrinter::~GCMetadataPrinter()'
rgc_printer.o:(.data.rel.ro._ZTIN12_GLOBAL__N_110RgcPrinterE+0x10): undefined reference to `typeinfo for llvm::GCMetadataPrinter'
collect2: error: ld returned 1 exit status
File "_none_", line 1:
Error: Error while building custom runtime system
make: **\* [rhine] Error 2

**Comment by artagnon** [comment]
Fixed now. Had to write out the constructor/ destructor for GCMetadataPrinter. I wonder why it was linking fine on OS X earlier. Can you confirm?
