### ISSUE TITLE
Will it create nice-sized standalone framework-less executables from Clojure-like code?

### ISSUE THREAD

**Issue by vi** [artagnon/rhine-ml#2]
Will basic `unistd`-only programs depend only on `libc`, or Ocaml or other big thing still need to be around for compiled program to work? Does it remove the "need to have heavy JVM around" requirement (so can make easy embedded code) or just changes it to "need to have <some other heavy thing> around"?

**Comment by artagnon** [comment]
Yes, it can easily be made to generate thin executables, although the current target is a JIT. The JIT itself is a pretty thin executable, which can be built using OCaml and OCaml-LLVM bindings.
