### ISSUE TITLE
Link errors on Linux

### ISSUE THREAD

**Issue by artagnon** [artagnon/rhine-ml#7]
Different link errors have been reported on Linux:

```
Error: Error on dynamically loaded library: ~/.opam/system/lib/llvm/./dllllvm.so:
undefined symbol: LLVMGetFirstUse.
```

```
~/.opam/system/lib/llvm/./libLLVMScalarOpts.a(ScalarReplAggregates.o): In function
`tryToMakeAllocaBePromotable(llvm::AllocaInst*, llvm::DataLayout const*)':
ScalarReplAggregates.cpp:(.text+0xc67): undefined reference to `operator delete(void*)'
```

**Comment by toroidal-code** [comment]
The first error is actually a pretty old problem on Linux. The easiest way to handle it is to by disabling shared libraries for the binary. Want me to make a PR?

We can see if that fixes the second issue.

**Comment by artagnon** [comment]
Sure, a PR would be sweet. I'm curious about why you didn't see the error though.

I think the second issue is about not finding the standard library?

**Comment by toroidal-code** [comment]
Probably because I've done some really hacky things with my shared library load path. 

I have no idea what to do about the second problem then. My experiences with the LLVM are only from the API at this point. Some of the stuff in Rhine is even beyond what I've played around with.

**Comment by toroidal-code** [comment]
I should note that over half the tests fail on my Linux machine because of `LLVM Error: Program used external function '...' which could not be resolved`. 
Where the functions are things like `println`, `cequ`, `print`, etc.
